elastic/elastic-otel-dotnet

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
> action: support  provenance in the pre-release workflow

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- nuget.config
- Adds the missing source for the push to the GH package repo. 
- Re-enables Feeds.io (unless we intended to leave that skipped @Mpdreamz). 
- Captitalises the first word in step names.
> Fix `release-main` action

- examples/Example.MinimalApi/appsettings.json
- src/Elastic.OpenTelemetry/Diagnostics/LoggerMessages.cs
- src/Elastic.OpenTelemetry/Diagnostics/Logging/CompositeLogger.cs
- src/Elastic.OpenTelemetry/Diagnostics/Logging/LogState.cs
- src/Elastic.OpenTelemetry/ElasticOpenTelemetryBuilder.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Processors/ElasticCompatibilityProcessor.cs
- src/Elastic.OpenTelemetry/Processors/TransactionIdProcessor.cs
- src/Elastic.OpenTelemetry/SemanticConventions/TraceSemanticConventions.cs
- tests/Elastic.OpenTelemetry.EndToEndTests/README.md
- tests/Elastic.OpenTelemetry.Tests/Processors/ElasticCompatibilityProcessorTests.cs
Fixes #80
The `ElasticCompatibilityProcessor` is used to apply legacy semantic conventions that may be missing on spans for applications which apply the latest conventions. This can cause UI issues in some cases since intake relies on the legacy attributes to map data to the Elastic format. That will be fixed in [apm-data](https://github.com/elastic/apm-data). Introducing this processor provides a more rapid solution for consumers until the intake mapping is updated.
> Add ElasticCompatibilityProcessor

- src/Elastic.OpenTelemetry/Diagnostics/LoggingEventListener.cs
This avoids wasted allocations preparing the log message string is no loggers are actually enabled.
> Check logging enabled before preparing OTel log message

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: github-early-access/generate-build-provenance has been deprecated in favor of 
actions/attest-build-provenance.
If there are any questions, please reach out to the @elastic/observablt-ci
> github-action: use actions/attest-build-provenance

- tests/Elastic.OpenTelemetry.EndToEndTests/DistributedFixture/ApmUIBrowserContext.cs
- tests/Elastic.OpenTelemetry.EndToEndTests/DistributedFixture/DotNetRunApplication.cs
This fixes the E2E tests to filter for our servicename prior to selecting it in the service overview.
We have a lot of new neighbors on the shared serverless project now 😸
> Fix E2E tests on CI

- .github/workflows/e2e.yml
Migrate to new oblt-cli actions to use the latest oblt-cli version that needs GCP to access cluster secrets
> Use new oblt-cli actions

- src/Elastic.OpenTelemetry/Elastic.OpenTelemetry.csproj
- src/Elastic.OpenTelemetry/ElasticOpenTelemetryBuilder.cs
- src/Elastic.OpenTelemetry/Extensions/ResourceBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Resources/HostDetector.cs
- src/Elastic.OpenTelemetry/SemanticConventions/ResourceSemanticConventions.cs
- tests/Elastic.OpenTelemetry.Tests/Resources/ResourceAttributeTests.cs
- tests/Elastic.OpenTelemetry.Tests/TransactionIdProcessorTests.cs
With this PR, we ensure that we always add a `service.instance.id` if not configured by the user. This is required since we likely want to use this in the dashboard, and the SDK does not always set it. It only gets set when `AddService` is used and not, for example, if a service name is provided via an environment variable.
This also adds a `HostDetector`, which is modified from the [one in the contrib repo](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/44c8576ef1290d9fbb6fbbdc973ae1b344afb4c2/src/OpenTelemetry.ResourceDetectors.Host/HostDetector.cs). The `host.id` detection is not yet in a released alpha package. I propose we include this code in our distro until that package is more mature and includes the `host.id`.
> Enhance resource attributes

- examples/Example.MinimalApi/appsettings.json
- src/Elastic.OpenTelemetry/Configuration/ElasticOpenTelemetryOptions.cs
- src/Elastic.OpenTelemetry/Configuration/EnvironmentVariables.cs
- src/Elastic.OpenTelemetry/Configuration/LogTargets.cs
- src/Elastic.OpenTelemetry/Diagnostics/LoggerMessages.cs
- src/Elastic.OpenTelemetry/Diagnostics/Logging/AgentLoggingHelpers.cs
- src/Elastic.OpenTelemetry/Diagnostics/Logging/FileLogger.cs
- src/Elastic.OpenTelemetry/Diagnostics/Logging/LogLevelHelpers.cs
- src/Elastic.OpenTelemetry/Diagnostics/LoggingEventListener.cs
- tests/Elastic.OpenTelemetry.Tests/Configuration/ElasticOpenTelemetryOptionsTests.cs
- tests/Elastic.OpenTelemetry.Tests/Configuration/GlobalLogConfigurationTests.cs
This ensure the same environment configuration keys exist in both the old and new agent:
https://github.com/elastic/apm-agent-dotnet/pull/2371
* ELASTIC_OTEL_LOG_LEVEL
* ELASTIC_OTEL_LOG_DIRECTORY
* ELASTIC_OTEL_LOG_TARGETS
Including the same defaulting behaviour (copy pasted the tests from that PR into this).
The default is no global logging unless any of these are set to a value other than:
`ELASTIC_OTEL_LOG_LEVEL=none` or `ELASTIC_OTEL_LOG_TARGETS=none`
`ELASTIC_OTEL_LOG_TARGETS=stdout` currently does not do anything, looking to tackle that in a follow up PR.
> Update logging envs and defaulting mechanism

- .github/workflows/e2e.yml
Vault free.
Tests are failing:
```
⚡️ FAIL  Elastic.OpenTelemetry.EndToEndTests.EndToEndTests.LatencyShowsAGraph
Error: System.TimeoutException : Timeout 30000ms exceeded.
Call log:
- waiting for GetByRole(AriaRole.Heading, new() { Name = "Services" }) to be visible
Failed Elastic.OpenTelemetry.EndToEndTests.EndToEndTests.LatencyShowsAGraph [2 s]
Error Message:
System.TimeoutException : Timeout 30000ms exceeded.
Call log:
- waiting for GetByRole(AriaRole.Heading, new() { Name = "Services" }) to be visible
Stack Trace:
at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 207
at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T] …
```
> github-actions: use github secrets

- .github/workflows/e2e.yml
Use OIDC Keyless to grab the required secrets in the Google Secret store 
https://github.com/elastic/elastic-otel-dotnet/pull/114 is the PR testing the e2e against the test feature branch
> ci: use secrets from the source of truth

- .github/workflows/bootstrap/action.yml
- .github/workflows/ci.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- build/patch-dotnet-auto-install.sh
- build/scripts/BuildInformation.fs
- build/scripts/CommandLine.fs
- build/scripts/Packaging.fs
- build/scripts/Targets.fs
- examples/Example.AutoInstrumentation/README.md
- examples/Example.AutoInstrumentation/distribution.Dockerfile
Continues #133 
This now puts all required distributions under `.artifacts/elastic-distribution`. 
This includes `elastic-*.zip` versions of the auto instrumentation zips. 
These zips include
* our plugin dll (twice for -windows.zip).
* `_instrument.sh` a copy of the original `instrument.sh`
* `instrument.sh` which sets our plugin var and calls `_instrument.sh`
This also includes elastic versions of the installation bash script and the powershell module to instrument and install/update on windows.
These files should now upload as part of our release and uploaded as artifacts on each commit in main.
Locally to build the distributables call:
```
./build.sh redistribute
````
To validate the distribution there is now a new dockerfile that validates our install and instrumentation scripts: …
> Distribution packaging continued

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- build/scripts/Packaging.fs
See: https://github.com/elastic/elastic-otel-dotnet/actions/runs/10185795296
Since the zips are 50megs total this will get excessive quick
This also guards that we only upload to a release when we are publishing a release.
Hopefully this will fix the glob issue here too: https://github.com/elastic/elastic-otel-dotnet/actions/runs/10185795294/job/28176108962
> Dont upload artifacts on each commit to main

- build/scripts/Packaging.fs
Our releases are not prefixed with `v` like the upstream distribution. 
So we need ensure we don't attempt to download our assets from releases prefixed with 'v'`.
> Replacing versions in urls should not include 'v' prefix.

- docs/configure.md
Update the configuration documentation to use the current naming for configuration settings.
> Fix configuration documentation

- .github/workflows/release.yml
- DockerFile
- Add container automation for autoinstrumentation.
- move release targets after container push
> Add container automation for auto instrumentation

- src/Elastic.OpenTelemetry/Processors/ElasticCompatibilityProcessor.cs
- tests/Elastic.OpenTelemetry.Tests/Processors/ElasticCompatibilityProcessorTests.cs
> Fix double question mark in http.target

- Elastic.OpenTelemetry.sln
- examples/Example.AspNetCore.Mvc/Dockerfile
- examples/Example.AspNetCore.Mvc/Example.AspNetCore.Mvc.csproj
- examples/k8s/README.md
- examples/k8s/elastic-otel-dotnet.yml
- examples/k8s/my-dotnet-application.yml
Ensuring our container for our autoinstrumentation distribution loads correctly
using the OpenTelemetry k8s Operator
Cc @akhileshpok
> k8s operator example and dev docs.

- .github/workflows/e2e.yml
Use the GitHub app to generate the required ephemeral tokens with the least permissive principle.
* Finer-grained tokens with Service Machine accounts are required to rotate the secrets manually.
* GitHub app to generate temporary tokens is the advanced approach to avoid the above
* Document what the GH workflow requires to run in terms of access
* GitHub Token with Permissions does not trigger GitHub builds 
Use `tibdex/github-app-token` with the required permissions and the repository scope
Configure the GH_TOKEN with the ephemeral token
> ci: use GitHub app for ephemeral tokens

- docs/configure.md
- global.json
- src/Elastic.OpenTelemetry/AutoInstrumentationPlugin.cs
- src/Elastic.OpenTelemetry/ElasticOpenTelemetryBuilder.cs
- src/Elastic.OpenTelemetry/Extensions/LoggingProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/MeterProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
We initially used UseOtlpExporter as a convenient way to enable OTLP export by default globally for all signals. However, this plays poorly with the AddOtlpExporter methods, which throw if called by consumer code. This change avoids that risk. It also introduces a LoggingProviderBuilder extension to register our defaults, which our main builder calls.
We still support disabling our default registration of the OTLP exporter via an environment variable, which the auto instrumentation plugin then passes when configuring the providers.
This PR also fixes a small typo in the docs.
Closes #177
> Refactor to use `AddOtlpExporter` and `LoggerProviderBuilder`

- README.md
- docs/get-started.md
This PR, if applied will
- Fix the links from the primary readme to the docs
- Fix the indentation in the code blocks in `get-started.md`
> Small docs fixes

- .github/workflows/e2e.yml
- build/scripts/Packaging.fs
- examples/Example.AutoInstrumentation/README.md
- src/Elastic.OpenTelemetry/AutoInstrumentationPlugin.cs
- src/Elastic.OpenTelemetry/Elastic.OpenTelemetry.csproj
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
- tests/Elastic.OpenTelemetry.EndToEndTests/DistributedFixture/ApmUIBrowserContext.cs
- tests/Elastic.OpenTelemetry.EndToEndTests/DistributedFixture/DistributedApplicationFixture.cs
- tests/Elastic.OpenTelemetry.EndToEndTests/ServiceTests.cs
Closes #123
Enables a default set of instrumentations when using the NuGet-based install method. For auto-instrumentation, we currently only enable the instrumentations shipped in the OTel auto instrumentation zip (i.e., Not `OpenTelemetry.Instrumentation.ElasticsearchClient`). We will review those once they are stable and potentially manually pull them into our customised zip files.
This also extended the retries for E2E, so hopefully, they will be less brittle in CI. It also takes additional screenshots, which help verify the Apm UI during E2E tests.
> Enable additional default instrumentation

- examples/Example.AspNetCore.Mvc/Controllers/HomeController.cs
- examples/Example.AspNetCore.Mvc/Program.cs
- examples/ServiceDefaults/ServiceDefaults.csproj
- src/Elastic.OpenTelemetry/Core/SignalBuilder.cs
- src/Elastic.OpenTelemetry/Diagnostics/LoggerMessages.cs
- src/Elastic.OpenTelemetry/Elastic.OpenTelemetry.csproj
- src/Elastic.OpenTelemetry/Extensions/MeterProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
On .NET 9, the BCL includes OTel-compliant instrumentation for HTTP, which is now preferred over using the contrib instrumentation. For .NET 9+ targets, we check if the contrib library is referenced, and if so, load that via reflection. Otherwise, we register the System.Net.Http source.
Closes #195
> Use native .NET 9 traces and metrics for HTTP instrumentation

- tests/AutoInstrumentation.IntegrationTests/PluginLoaderTests.cs
- tests/Directory.Build.props
- tests/Elastic.OpenTelemetry.EndToEndTests/DistributedFixture/ITrafficSimulator.cs
- tests/Elastic.OpenTelemetry.EndToEndTests/Elastic.OpenTelemetry.EndToEndTests.csproj
- tests/Elastic.OpenTelemetry.EndToEndTests/EndToEndOptions.cs
- tests/Elastic.OpenTelemetry.EndToEndTests/ServiceTests.cs
- tests/Elastic.OpenTelemetry.Tests/AutoInstrumentationPluginTests.cs
- tests/Elastic.OpenTelemetry.Tests/Configuration/ElasticOpenTelemetryOptionsTests.cs
- tests/Elastic.OpenTelemetry.Tests/Configuration/GlobalLogConfigurationTests.cs
- tests/Elastic.OpenTelemetry.Tests/Elastic.OpenTelemetry.Tests.csproj
- tests/Elastic.OpenTelemetry.Tests/GlobalUsings.cs
- tests/Elastic.OpenTelemetry.Tests/Processors/ElasticCompatibilityProcessorTests.cs
FluentAssertions v8 is moving to a paid model. This PR removes the use of this package so that we don't accidentally end up running a version outside of its license. We now prefer the xunit assertions.
> Remove use of FluentAssertions

- src/Elastic.OpenTelemetry/Core/AutoInstrumentationPlugin.cs
- src/Elastic.OpenTelemetry/Core/BuilderState.cs
- src/Elastic.OpenTelemetry/Core/GlobalProviderBuilderState.cs
- src/Elastic.OpenTelemetry/Core/SignalBuilder.cs
- src/Elastic.OpenTelemetry/Extensions/LoggingProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/MeterProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/OpenTelemetryBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/OpenTelemetryLoggerOptionsExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/ResourceBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
- tests/Elastic.OpenTelemetry.Tests/LoggingTests.cs
> Rename UseElasticDefaults to WithElasticDefaults

- .github/workflows/bootstrap/action.yml
- build/scripts/Targets.fs
- dotnet-tools.json
- examples/Example.AspNetCore.Mvc/Program.cs
- examples/Example.AspNetCore.Mvc/appsettings.json
- examples/ServiceDefaults/ServiceDefaults.csproj
- src/Elastic.OpenTelemetry.AutoInstrumentation/Elastic.OpenTelemetry.AutoInstrumentation.csproj
- src/Elastic.OpenTelemetry/Core/AutoInstrumentationPlugin.cs
- src/Elastic.OpenTelemetry/Core/SignalBuilder.cs
- src/Elastic.OpenTelemetry/Diagnostics/LoggerMessages.cs
- src/Elastic.OpenTelemetry/Elastic.OpenTelemetry.csproj
- src/Elastic.OpenTelemetry/Extensions/LoggingProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/MeterProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/OpenTelemetryBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/ResourceBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Instrumentation/ContribMetricsInstrumentation.cs
- src/Elastic.OpenTelemetry/Instrumentation/ContribResourceDetectors.cs
- tests/Elastic.OpenTelemetry.Tests/InstrumentationScanningTests.cs
This subscribes to additional metrics out of the box and reactors that code a little.
After an earlier refactoring, we were not setting the required resource attributes, which would cause breaks in the curated dashboard. This has been fixed.
> Metric enhancements and fix resource attributes

- src/Elastic.OpenTelemetry.Core/Extensions/TracerProvderBuilderExtensions.cs
- src/Elastic.OpenTelemetry.Core/Processors/ElasticCompatibilityProcessor.cs
On recent versions of APM server, this is no longer required.
Leaving the processor and methods in place (although unused) in case we need to reintroduce it in the future.
Closes #206
> Remove compatibility processor registration

- src/Elastic.OpenTelemetry.AutoInstrumentation/AutoInstrumentationPlugin.cs
- src/Elastic.OpenTelemetry.AutoInstrumentation/Elastic.OpenTelemetry.AutoInstrumentation.csproj
- src/Elastic.OpenTelemetry.Core/Exporters/ElasticUserAgentHandler.cs
- src/Elastic.OpenTelemetry.Core/Exporters/OtlpExporterDefaults.cs
- src/Elastic.OpenTelemetry.Core/Extensions/ResourceBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Elastic.OpenTelemetry.csproj
- src/Elastic.OpenTelemetry/Extensions/LoggingProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/MeterProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/OpenTelemetryBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
> Set Elastic User-Agent header on exporter options

- examples/Example.Console/Usage.cs
- src/Elastic.OpenTelemetry.Core/Configuration/CompositeElasticOpenTelemetryOptions.cs
- src/Elastic.OpenTelemetry/Extensions/HostApplicationBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/LoggingProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/MeterProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/OpenTelemetryBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/ServiceCollectionExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
- tests/Elastic.OpenTelemetry.Tests/Configuration/CompositeElasticOpenTelemetryOptionsTests.cs
- tests/Elastic.OpenTelemetry.Tests/Diagnostics/LoggingTests.cs
- tests/Elastic.OpenTelemetry.Tests/Extensions/HostApplicationBuilderTests.cs
- tests/Elastic.OpenTelemetry.Tests/Extensions/ServiceCollectionTests.cs
This PR removes some redundant public extension methods for skipping OtlpExporter registration, preferring the extensions that accept an `ElasticOpenTelemetryOptions` instance. Removing these avoids confusion and simplifies documentation.
This also adds null checks and exception XML docs for the `ServiceCollectionExtensions`.
> Refine public extension methods

- build/patch-dotnet-auto-install.sh
This is the same fix as upstream here, which allows use of wget when curl isn't available, helpful on the runtime docker images. https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/4076
I tested it with a copy like below
wget and not curl 
```bash
$ docker run --rm -it mcr.microsoft.com/dotnet/runtime:8.0-alpine
/ # sh -xc "$(wget -qO- https://gist.githubusercontent.com/codefromthecrypt/77865a27ad40dc4fa7ef35396a0ba4dc/raw/fa516690ee5afad5d53f1c4e7671a47a207b24d1/elastic-dotnet-auto-
install.sh)"
+ set -e
+ '[' -z  ]
+ uname -s
+ tr '[:upper:]' '[:lower:]'
+ ldd /bin/ls
+ grep -m1 musl
+ '[' ' /lib/ld-musl-aarch64.so.1 (0xfe39c41a3000)' ]
+ OS_TYPE=linux-musl
+ '[' -z  ]
+ uname -m
+ ARCHITECTURE=arm64
+ command -v curl
+ command -v wget
+ DOWNLOADER='wget -qO'
+ …
```
> allow wget in elastic-dotnet-auto-install.sh

- examples/Example.AspNetCore.Mvc/appsettings.json
- examples/Example.Console/Example.Console.csproj
- examples/Example.Console/Program.cs
- examples/Example.Console/Usage.cs
- src/Elastic.OpenTelemetry.AutoInstrumentation/AutoInstrumentationPlugin.cs
- src/Elastic.OpenTelemetry.Core/Extensions/ResourceBuilderExtensions.cs
- src/Elastic.OpenTelemetry.Core/Extensions/TracerProvderBuilderExtensions.cs
- src/Elastic.OpenTelemetry.Core/SignalBuilder.cs
- src/Elastic.OpenTelemetry/Extensions/ResourceBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
It also renames a few types and marks the processor extensions internal for now.
> Fix missing resource attributes

- src/Elastic.OpenTelemetry/Extensions/MeterProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Instrumentation/ContribMetricsInstrumentation.cs
- tests/Elastic.OpenTelemetry.Tests/InstrumentationScanningTests.cs
> Prefer meter registration via scanning with special case for .NET 9

- src/Elastic.OpenTelemetry.Core/Diagnostics/LoggerMessages.cs
- src/Elastic.OpenTelemetry.Core/Instrumentation/ContribResourceDetectors.cs
- src/Elastic.OpenTelemetry.Core/Instrumentation/InstrumentationAssemblyInfo.cs
- src/Elastic.OpenTelemetry.Core/SignalBuilder.cs
- src/Elastic.OpenTelemetry/Extensions/TracerProviderBuilderExtensions.cs
- src/Elastic.OpenTelemetry/Instrumentation/ContribMetricsInstrumentation.cs
- src/Elastic.OpenTelemetry/Instrumentation/ContribTraceInstrumentation.cs
> Simplify reflection to work on classic ASP.NET and singlefile publish

- Directory.Build.props
We depend on some unstable instrumentation packages and must ignore the `NU5104` warning to allow `dotnet pack` to generate the packages.
> Ignore warning for unstable dependencies

- .github/workflows/bootstrap/action.yml
- tests/Elastic.OpenTelemetry.Tests/Diagnostics/LoggingTests.cs
- tests/Elastic.OpenTelemetry.Tests/TestLogger.cs
Our tags are not prefixed with "v", so this command wasn't finding the expected version.
> Remove invalid prefix from minver cmd

- src/Elastic.OpenTelemetry.Core/Diagnostics/LoggerMessages.cs
- src/Elastic.OpenTelemetry.Core/Extensions/OpenTelemetryLoggerOptionsExtensions.cs
- src/Elastic.OpenTelemetry/Extensions/LoggingProviderBuilderExtensions.cs
Due to spec non-compliance in the upstream SDK, this can cause issues when sent through the EDOT collector and the managed OTLP endpoint.
We'll reenable it in a future release once upstream is fixed.
Lessens the impact of #263. 
The main fix needs to occur upstream.
> No longer default to IncludeScopes

- README.md
- src/Elastic.OpenTelemetry.Core/Diagnostics/LoggerMessages.cs
This updates links to EDOT docs (when ready). To be merged by Fabri, but please preapprove.
> Update links to EDOT docs

- src/Elastic.OpenTelemetry.Core/Diagnostics/LoggerMessages.cs
- src/Elastic.OpenTelemetry.Core/Diagnostics/LoggingEventListener.cs
- tests/Elastic.OpenTelemetry.Tests/Diagnostics/LoggingTests.cs
When using SDK diagnostics, the lowest supported log level for OTEL_LOG_LEVEL is 'debug'. To align with this, we emit verbose logs captured by the EventListener under debug.
This change also updates the logger messages to not use trace level and prefer debug in those cases. This make diagnostics and support easier as we only need to instruct the customer to use the levels as supported upstream.
> Treat EventLevel.Verbose as debug log level

- examples/Example.AutoInstrumentation/Dockerfile
- tests/AutoInstrumentation.IntegrationTests/PluginLoaderTests.cs
Fixes #298
- Updates the dockerfile used to create an image with the example application and autoinstrumentation plugin.
- Update to the latest upstream OTel release
- Ensure we use the expected SDK and runtime (.NET 9) for the stages
- Ensure we copy the AutoInstrumentation dll into the final stage
- Fix incorrect folder for the extracted auto instrumentation directory created by the OTel installer
- Updates the test assertions based on logging changes
> Fix dockerfile for PluginLoaderTests
